version: "2"

run:
  timeout: 5m
  tests: true

linters:
  disable:
    - dupl
    - errcheck
    - goconst
    - gosec
    - revive
  enable:
    # - gocyclo  # Disabled: high complexity acceptable for large functions (see LINTING.md)
    - misspell
    - unconvert
    - unparam

linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - (*database/sql.DB).Close
      - (*database/sql.Rows).Close
      - (*database/sql.Tx).Rollback
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  revive:
    rules:
      - name: var-naming
      - name: exported

issues:
  exclude:
    - "var-naming: avoid meaningless package names"
    - "exported.*SQLiteStorage.*stutters"
    - "G201: SQL string formatting"
    - "G301: Expect directory permissions"
    - "G204: Subprocess launched"
    - "G115: integer overflow conversion"
    - "G304.*file inclusion via variable"
